dependency<-function()
{
  require(bnlearn)
  require(rhandsontable)
  require(shiny)
  require(shinydashboard)
  require(dplyr)
  require(visNetwork)
  require(shinyWidgets)
  require(missRanger)
  require(tools)
  require(shinyalert)
  require(shinycssloaders)
  require(rintrojs)
  require(arules)
  require(psych)
  require(DescTools)
  require(DT)
  require(linkcomm)
  require(igraph)
  require(parallel)
  require(snow)
  require(shinyBS)
  if(require('gRbase')==F)
  {
    install.packages('gRbase')
  }
  if(require('gRain')==F)
  {
    install.packages('gRain')
  }
}
